<a href="https://colab.research.google.com/github/Khalidzo/digit-recognition/blob/main/Make_your_own_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy

In [17]:
class neuralNetwork:
  def __init__(self, input, hidden, output, learning_rate):
    self.input = input
    self.hidden = hidden
    self.output = output

    self.lr = learning_rate

    # NN layers
    self.wih = numpy.random.rand(self.hidden, self.input) - 0.5
    self.who = numpy.random.rand(self.output, self.hidden) - 0.5

  def train():
    pass

  def query():
    pass

In [18]:
# layers
input_nodes = 3
hidden_nodes = 3
output_nodes = 3

# set learning rate
learning_rate = 0.3

# instantiate the NN
n = neuralNetwork(input_nodes, hidden_nodes, output_nodes, learning_rate)

In [19]:
print(n.wih)

[[ 0.31557495 -0.30516457 -0.31664893]
 [-0.04181107 -0.1359757   0.44619595]
 [-0.03175868 -0.01131925 -0.42418611]]


In [20]:
print(n.who)

[[ 0.49147519  0.42661145 -0.01954162]
 [-0.39264356  0.28865613 -0.23801401]
 [-0.47335686 -0.48010728  0.33178601]]
